[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.21"
http = "0.2.8"
http-body = "0.4.5"
hyper = "0.14.20"
tower = { version = "0.4.13", features = ["util"] }
pin-project-lite = "0.2.9"
