[package]
name = "generated"
version = "0.1.0"
edition = "2021"

[dependencies]
runtime = { path = "../runtime" }

futures = "0.3.21"
http = "0.2.8"
http-body = "0.4.5"
hyper = "0.14.20"
tower = "0.4.13"
pin-project-lite = "0.2.9"

[dev-dependencies]
hyper = { version = "0.14.20", features = ["server", "http2", "tcp"] }
